[package]
name = "dtos"
version = "0.1.0"
edition = "2024"

[dependencies]
entity = { path = "../entity" }
services = { path = "../services" }
serde = { workspace = true }
sea-orm = { workspace = true }
argon2 = { workspace = true }
anyhow = { workspace = true }
regex = "1.12.3"

[lints]
workspace = true
