[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
sea-orm = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
sea-orm = { workspace = true, features = ["mock"] }
