name: Rust ci

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-with-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout submodule
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Build project
        run: cargo build --verbose --workspace
  build:
    runs-on: ubuntu-latest
    env:
      NO_WEB: 1
    steps:
      - name: Checkout submodule
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Build project
        run: cargo build --verbose --workspace
  clippy:
    runs-on: ubuntu-latest
    env:
      NO_WEB: 1
    steps:
      - name: Checkout submodule
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Build project
        # running this with --verbose outputs a lot of information that is not necessary
        run: cargo clippy --workspace
  test:
    runs-on: ubuntu-latest
    env:
      NO_WEB: 1
    steps:
      - name: Checkout submodule
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Run tests
        run: cargo test --verbose --workspace
